server {
    listen 80;
    server_name relay.superlearn.ing;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 200 'nginx running';
        add_header Content-Type text/plain;
    }
}
