
server {
  listen 80;
  server_name localhost;

  location / {
    proxy_pass http://email-api:3000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
} 

server {
  listen 80;
  server_name smtp.superlearn.ing;

  location /.well-known/acme-challenge/ {
    root /var/www/html;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name relay.superlearn.ing;

  ssl_certificate /etc/letsencrypt/live/relay.superlearn.ing/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/relay.superlearn.ing/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;

  location / {
    proxy_pass http://email-api:3000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
