server {
    listen 443 ssl;
    server_name relay.superlearn.ing;

    ssl_certificate /etc/letsencrypt/live/relay.superlearn.ing/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/relay.superlearn.ing/privkey.pem;

    location / {
        proxy_pass http://email-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name relay.superlearn.ing;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 200 'nginx running';
        add_header Content-Type text/plain;
    }
}
